version: '3.8'

services:
  taskflow-ai:
    build: .
    container_name: taskflow-ai-dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - taskflow-network
    volumes:
      # Mount source for development
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./main.js:/usr/share/nginx/html/main.js:ro
      - ./manual.html:/usr/share/nginx/html/manual.html:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
      - ./core:/usr/share/nginx/html/core:ro
      - ./features:/usr/share/nginx/html/features:ro
      - ./services:/usr/share/nginx/html/services:ro
      - ./ui:/usr/share/nginx/html/ui:ro

  # Optional: Include Ollama service for local AI
  ollama:
    image: ollama/ollama:latest
    container_name: taskflow-ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - taskflow-network
    profiles:
      - with-ollama

volumes:
  ollama_data:
    driver: local

networks:
  taskflow-network:
    driver: bridge
