version: '3.8'

services:
  taskflow-ai:
    build: .
    container_name: taskflow-ai
    network_mode: host
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  taskflow-network:
    driver: bridge
