version: '3.8'

services:
  taskflow-ai:
    build: .
    container_name: taskflow-ai
    ports:
      - "8080:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - DATABASE_PATH=/app/data/taskflow.db
      - EXTERNAL_HOST=${EXTERNAL_HOST:-localhost}
      - EXTERNAL_PORT=${EXTERNAL_PORT:-8080}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:8080}
      - AUTH_RATE_LIMIT_WINDOW_MS=${AUTH_RATE_LIMIT_WINDOW_MS:-300000}
      - AUTH_RATE_LIMIT_MAX_REQUESTS=${AUTH_RATE_LIMIT_MAX_REQUESTS:-50}
      - DATA_RATE_LIMIT_WINDOW_MS=${DATA_RATE_LIMIT_WINDOW_MS:-900000}
      - DATA_RATE_LIMIT_MAX_REQUESTS=${DATA_RATE_LIMIT_MAX_REQUESTS:-200}
    volumes:
      - taskflow_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - taskflow-network

  # Optional: Include Ollama service for local AI
  ollama:
    image: ollama/ollama:latest
    container_name: taskflow-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - taskflow-network
    profiles:
      - with-ollama

volumes:
  taskflow_data:
    driver: local
  ollama_data:
    driver: local

networks:
  taskflow-network:
    driver: bridge
